print("Please fill in the blanks below:")
print("_(name)_'s favorite video game is _(subject)_.")
user_name = input("What is your name? ")
favorite_game = input("What is your favorite game? ")
print("%s's favorite game is %s." % (user_name, favorite_game))